name: deploy

on:
  push:
    branches: [main]

jobs:
  test:
    uses: ./.github/workflows/test.yml
    secrets:
      GH_API_URL: ${{ secrets.GH_API_URL }}
      GH_API_TOKEN: ${{ secrets.GH_API_TOKEN }}
  deploy:
    needs: test
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        node-version: [18.13.0]
    steps:
      - uses: actions/checkout@v2
      - name: Install pnpm
        run: npm install -g pnpm
      - name: Install Vercel CLI
        run: npm install --global vercel@latest
      - name: Pull Vercel Environment Information
        run: vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}
      - name: Build Project Artifacts
        run: vercel build --prod --token=${{ secrets.VERCEL_TOKEN }}
      - name: Deploy Project Artifacts to Vercel
        run: vercel deploy --prebuilt --prod --token=${{ secrets.VERCEL_TOKEN }}
